Importing libraries

In [26]:
# Warning : the backend below may generate some issues if used
# in a conda environment.
%matplotlib tk
# Try this backend if %matplotlib tk does not work properly
# In this case do not use the ginput command.
#%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from scipy import linalg

import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

Enter dimensions of soccer field

In [27]:
goal_width=7.32
goal_height=2.44
goal_area_1=5.5
goal_area_2=18.32
penalty_area_1=16.5
penalty_area_2=40.32
corner_arc=1
flag_height=1.5
field_1=65
field_2=105

Enter 3D point coordinates - Goal-> Goal area -> Penalty area -> Corners -> Corner radius points -> Flag extremity

In [29]:
        # Goal
u_field=np.array([[goal_width/2,0,0],[goal_width/2,goal_height,0],   
        [-goal_width/2,goal_height,0],[-goal_width/2,0,0],            
        # Goal
        [goal_area_2/2,0,0],[goal_area_2/2,0,goal_area_1],           
        # Goal area
        [-goal_area_2/2,0,goal_area_1],[-goal_area_2/2,0,0],
        # Goal area
        [penalty_area_2/2,0,0],[penalty_area_2/2,0,penalty_area_1],
        # Penalty area
        [-penalty_area_2/2,0,penalty_area_1],[-penalty_area_2/2,0,0],
        # Penalty area
        [field_1/2,0,0],[-field_1/2,0,0], # Corners
        [field_1/2-corner_arc,0,0],[-field_1/2+corner_arc,0,0],
        # Corner radius x
        [field_1/2,0,corner_arc],[-field_1/2,0,corner_arc],
        # Corner radius y
        [field_1/2,flag_height,0],[-field_1/2,flag_height,0]])
        # Flag extremities
print(u_field)

[[  3.66   0.     0.  ]
 [  3.66   2.44   0.  ]
 [ -3.66   2.44   0.  ]
 [ -3.66   0.     0.  ]
 [  9.16   0.     0.  ]
 [  9.16   0.     5.5 ]
 [ -9.16   0.     5.5 ]
 [ -9.16   0.     0.  ]
 [ 20.16   0.     0.  ]
 [ 20.16   0.    16.5 ]
 [-20.16   0.    16.5 ]
 [-20.16   0.     0.  ]
 [ 32.5    0.     0.  ]
 [-32.5    0.     0.  ]
 [ 31.5    0.     0.  ]
 [-31.5    0.     0.  ]
 [ 32.5    0.     1.  ]
 [-32.5    0.     1.  ]
 [ 32.5    1.5    0.  ]
 [-32.5    1.5    0.  ]]


Keep points that are visible in the image buffer

In [30]:
    # Goal
u_w=np.array([[goal_width/2,0,0],[goal_width/2,goal_height,0],
    # Goal
    [-goal_width/2,goal_height,0],[-goal_width/2,0,0],
    # Goal area
    [goal_area_2/2,0,0],[goal_area_2/2,0,goal_area_1],
    # Goal area
    [-goal_area_2/2,0,goal_area_1],[-goal_area_2/2,0,0],
    # Penalty area
    [-penalty_area_2/2,0,0],
    # Corners
    [-field_1/2,0,0],
    # Corner radius x
    [-field_1/2+corner_arc,0,0],
    # Corner radius y
    [-field_1/2,0,corner_arc],
    # Flag extremities
    [-field_1/2,flag_height,0]])          

# Number of visible points
N=np.shape(u_w)[0]
# Transformation to homogeneous coordinates
u_w= np.vstack((np.transpose(u_w),np.ones(N)))

Show 3D cloud of points

In [31]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(u_w[0,:],-u_w[2,:],u_w[1,:])
ax.set_xlim(-35, 35)
ax.set_zlim(-10, 1)
ax.set_ylim(-2,10)
plt.show()

Get image buffer points manually

In [32]:
img=mpimg.imread('goal.jpg')
fig,ax = plt.subplots()
ax.imshow(img)

# If %matplotlib works properly you can
# use the following two lines
# Image buffer points from mouse clicks
u_im = np.array(plt.ginput(N,timeout=-1))
plt.close()

# If you %matplotlib does not work properly
# you can try the code below
#u_im= np.array([]).reshape(0,2)
#def onclick(event):
#    global ix, iy
#    ix, iy = event.xdata, event.ydata
    
#    global u_im
#    u_im = np.vstack((u_im,np.array([[ix,iy]])))

#    if np.shape(u_im)[0] == 13:
#        fig.canvas.mpl_disconnect(cid)
#        plt.close()
        
#cid = fig.canvas.mpl_connect('button_press_event', onclick)

In [8]:
print(u_im)

[[1658.32862903  984.04919355]
 [1419.70362903  741.57540323]
 [1427.40120968  410.57943548]
 [1685.27016129  603.01895161]
 [1877.70967742 1191.88387097]
 [ 957.84879032 1203.43024194]
 [ 569.12096774  622.26290323]
 [1269.60080645  618.4141129 ]
 [1027.12701613  391.33548387]
 [ 807.74596774  183.50080645]
 [ 792.35080645  164.25685484]
 [ 707.67741935  175.80322581]
 [ 796.19959677   21.8516129 ]]


Show image point coordinates in homogeneous coordinates

In [33]:
u_im = np.vstack((np.transpose(u_im),np.ones(N)))
print(u_im)

[[1.65832863e+03 1.68142137e+03 1.42355242e+03 1.42740121e+03
  1.88155847e+03 9.57848790e+02 5.57574597e+02 1.27344960e+03
  1.02712702e+03 7.96199597e+02 8.15443548e+02 7.15375000e+02
  8.03897177e+02]
 [9.91746774e+02 6.10716532e+02 4.14428226e+02 7.45424194e+02
  1.19188387e+03 1.21112782e+03 6.29960484e+02 6.14565323e+02
  3.87486694e+02 1.71954435e+02 1.87349597e+02 1.71954435e+02
  2.18516129e+01]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]]


Show chosen points

In [10]:
# Change backend if necessary
#%matplotlib inline

In [34]:
fig,ax = plt.subplots()
ax.imshow(img)
plt.scatter(u_im[0,:],u_im[1,:])
plt.show()

Centering and scaling

3D points

In [12]:
s_w    =1./(np.std(u_w,1,keepdims=True)[0:3])# Scaling
t_w    =-(np.mean(u_w,1,keepdims=True)[0:3]) # Translation
diag_s =np.diag(np.squeeze(s_w))
# Stacking scaling and translation
T_w    =np.array(np.hstack((diag_s,t_w*s_w)))
T_w    =np.vstack((T_w,np.array([0,0,0,1])))
print(T_w)

[[ 0.06329239  0.          0.          0.72620717]
 [ 0.          1.08582757  0.         -0.53289076]
 [ 0.          0.          0.50775827 -0.46869994]
 [ 0.          0.          0.          1.        ]]


Image buffer points

In [13]:
s_im   =1./(np.std(u_im,1,keepdims=True)[0:2]) # Scaling
t_im   =-(np.mean(u_im,1,keepdims=True)[0:2])  # Translation
diag_s =np.diag(np.squeeze(s_im))
# Stacking scaling and translation
T_im   =np.array(np.hstack((diag_s,t_im*s_im)))
T_im   =np.vstack((T_im,np.array([0,0,1])))
print(T_im)

[[ 2.43439403e-03  0.00000000e+00 -2.80818300e+00]
 [ 0.00000000e+00  2.67152838e-03 -1.50262417e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Transformed 3D points and buffer points

In [14]:
u_w_t = np.dot(T_w,u_w)   # Transformed 3D points
u_im_t= np.dot(T_im,u_im) # Transformed image buffer points

Construction of the A matrix for DLT

In [15]:
u_w_i=np.transpose(u_w_t[:,0].reshape(-1,1))
A_i_1=np.hstack((np.zeros((1,4)),-u_w_i,u_im_t[1,0]*u_w_i))
A_i_2=np.hstack((u_w_i,np.zeros((1,4)),-u_im_t[0,0]*u_w_i))
A    = np.vstack((A_i_1,A_i_2))
# Stacking matrices for each point correspondence
for i in range(1,N):    
    u_w_i=np.transpose(u_w_t[:,i].reshape(-1,1))
    A_i_1=np.hstack((np.zeros((1,4)),-u_w_i,u_im_t[1,i]*u_w_i))
    A_i_2=np.hstack((u_w_i,np.zeros((1,4)),-u_im_t[0,i]*u_w_i))
    A    = np.vstack((A,A_i_1,A_i_2))

Solution using the SVD

In [16]:
U,S,V = np.linalg.svd(A) # SVD
m_t   = V[11,:]          # Last row of V, 
                         # since python's V is the transpose
                         # of the SVD's V 
print(m_t)

[-0.50164     0.06256396  0.35749295  0.08902465 -0.52797793  0.13196275
 -0.02844511  0.09683147  0.11034956  0.00249865 -0.01903982 -0.53834037]


Reshape to get M_t

In [17]:
M_t   = m_t.reshape(3,4)
print(M_t)

[[-0.50164     0.06256396  0.35749295  0.08902465]
 [-0.52797793  0.13196275 -0.02844511  0.09683147]
 [ 0.11034956  0.00249865 -0.01903982 -0.53834037]]


Transform to get M

In [18]:
M = np.dot(np.linalg.inv(T_im),np.dot(M_t,T_w))

Rescale to get three first elements of third row with unitary norm

In [19]:
M = -M/np.linalg.norm(M[2,0:3])
print(M)

[[ 4.07608079e+02 -2.53738532e+03 -5.18447133e+03  5.84893850e+04]
 [ 7.01495887e+02 -4.50987344e+03  8.86579137e+02  3.12361438e+04]
 [-5.71018576e-01 -2.21816823e-01  7.90401849e-01  3.68408944e+01]]


Getting Intrinsic and rotation matrices with RQ decomposition

In [20]:
M_int, R = linalg.rq(M[:,0:3])
print(M_int)
print(R)

[[-3.46710777e+03  2.69565671e+03  3.76773276e+03]
 [ 0.00000000e+00  4.46381462e+03 -1.30055241e+03]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00]]
[[ 0.75450135  0.23762564  0.61176938]
 [ 0.32352048 -0.94569094 -0.03167244]
 [ 0.57101858  0.22181682 -0.79040185]]


Change signs of columns of M_int
and corresponding rows of R if necessary

In [21]:
#M_int[:,0] = -M_int[:,0]
#R[0,:] = -R[0,:]
#M_int[:,1] = -M_int[:,1]
#R[1,:] = -R[1,:]
#M_int[:,2] = -M_int[:,2]
#R[2,:] = -R[2,:]
print(M_int)
print(R)

[[-3.46710777e+03  2.69565671e+03  3.76773276e+03]
 [ 0.00000000e+00  4.46381462e+03 -1.30055241e+03]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00]]
[[ 0.75450135  0.23762564  0.61176938]
 [ 0.32352048 -0.94569094 -0.03167244]
 [ 0.57101858  0.22181682 -0.79040185]]


Checking determinant of the rotation matrix

In [22]:
print(np.linalg.det(R))

0.9999999999999999


Project points on the image buffer using the estimated camera matrix

In [23]:
u_sim=np.dot(M,u_w)
u_sim=u_sim/u_sim[2,:]

fig,ax = plt.subplots()
ax.imshow(img)
plt.scatter(u_sim[0,:],u_sim[1,:])
plt.show()

Evaluate translation vector

In [24]:
t=np.linalg.solve(M_int,M[:,3])
print(-np.dot(R.T,t))

[67.37219195 18.8510742   7.35241713]


In [25]:
print(M)

[[ 4.07608079e+02 -2.53738532e+03 -5.18447133e+03  5.84893850e+04]
 [ 7.01495887e+02 -4.50987344e+03  8.86579137e+02  3.12361438e+04]
 [-5.71018576e-01 -2.21816823e-01  7.90401849e-01  3.68408944e+01]]
